- src: git+https://github.com/meteorfox/ansible-rally.git
  name: ansible-rally

- src: git+https://github.com/meteorfox/pcp-ansible.git
  name: pcp-ansible

- src: git+https://github.com/rossmcdonald/telegraf.git
  name: rossmcdonald.telegraf

- src: git+https://github.com/vhe182/ansible-influxdb.git
  name: influxdb

- src: git+https://github.com/kbrebanov/ansible-chronograf.git
  name: kbrebanov.chronograf

- src: git+https://github.com/geerlingguy/ansible-role-jenkins.git
  name: geerlingguy.jenkins
